### ISSUE TITLE
ライントレースを行う

### ISSUE THREAD

**Issue by molpui0726** [KatLab-MiyazakiUniv/etrobocon2023#37]
## 完了条件
ライントレースを行うクラスを作成する。

## 実現方法
具体的には、指定距離ライントレースのDistanceLineTracingと、指定色ライントレースのColorLineTracingを実装する。
これらは具体的な動作なので基底クラスで実装する。

**Comment by miyashita64** [comment]
DistanceLineTracingとColorLineTracingの実装に向けて、その規定クラスとなるLineTracing(この命名はテキトー)を実装して欲しい。
LineTracingを実装した上で、DistanceLineTracingとColorLineTracing実装してくれるならありがたいけど、ちょっと重いかも。
